use_frameworks!

target 'GopherCache_Example' do
  pod 'GopherCache', :path => '../'

  target 'GopherCache_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
